<?php
$dd=base_url();
?>
	
	  <script src="<?=$dd?>design/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?=$dd?>design/global/scripts/datatable.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?=$dd?>design/global/plugins/bootstrap-toastr/toastr.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?=$dd?>design/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->


        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?=$dd?>design/global/plugins/moment.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/morris/morris.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/morris/raphael-min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/counterup/jquery.waypoints.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/counterup/jquery.counterup.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amcharts/serial.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amcharts/pie.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amcharts/radar.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amcharts/themes/light.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amcharts/themes/patterns.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amcharts/themes/chalk.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/ammap/ammap.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/ammap/maps/js/worldLow.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/amcharts/amstockcharts/amstock.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/horizontal-timeline/horizontal-timeline.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/flot/jquery.flot.categories.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<?=$dd?>design/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->


        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?=$dd?>design/pages/scripts/table-datatables-managed.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?=$dd?>design/global/plugins/bootstrap-multiselect/js/bootstrap-multiselect.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->

        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?=$dd?>design/pages/scripts/components-bootstrap-multiselect.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->

        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?=$dd?>design/pages/scripts/ui-toastr.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?=$dd?>design/pages/scripts/dashboard.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="<?=$dd?>design/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <script src="<?=$dd?>design/layouts/global/scripts/quick-nav.min.js" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->
        <script>
            $(document).ready(function()
            {
                toastr.options = {
                "closeButton": true,
                "debug": false,
                "positionClass": "toast-top-right",
                "onclick": null,
                "showDuration": "1000",
                "hideDuration": "1000",
                "timeOut": "3000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
                $('#clickmewow').click(function()
                {
                    $('#radio1003').attr('checked', 'checked');
                });
            })
        </script>