// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARriDSPlxAs5Xn-D8tpT0dbply0fFqsiU',
    appId: '1:378009877139:web:12d008d4fd37c4cbd3ab66',
    messagingSenderId: '378009877139',
    projectId: 'mersaty-4ecb4',
    authDomain: 'mersaty-4ecb4.firebaseapp.com',
    storageBucket: 'mersaty-4ecb4.appspot.com',
    measurementId: 'G-768G9EM1EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2VzwEvOG_y0yAOdNgAXlWTyUgSRs9-A',
    appId: '1:378009877139:android:cea7d4774a8452acd3ab66',
    messagingSenderId: '378009877139',
    projectId: 'mersaty-4ecb4',
    storageBucket: 'mersaty-4ecb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFxboAprxPaDQDx_RZvc4whQUX-4XFyQ',
    appId: '1:378009877139:ios:f22523b873033b6cd3ab66',
    messagingSenderId: '378009877139',
    projectId: 'mersaty-4ecb4',
    storageBucket: 'mersaty-4ecb4.appspot.com',
    iosBundleId: 'com.active.wasselni',
  );

}